# Generated by Django 2.2.2 on 2019-10-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_carlson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocation',
            name='weighting',
            field=models.CharField(default='', max_length=10),
        ),
    ]
