# Generated by Django 2.2.2 on 2019-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_carlson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='corrector',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
