# Generated by Django 2.2.2 on 2019-10-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0001_initial'),
        ('dcodex_carlson', '0002_auto_20191012_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='manuscript',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcodex.Manuscript'),
        ),
    ]
