# Generated by Django 2.2.2 on 2019-10-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_carlson', '0003_witness_manuscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='macros',
            field=models.ManyToManyField(blank=True, to='dcodex_carlson.Macro'),
        ),
        migrations.AlterField(
            model_name='location',
            name='verse_labels',
            field=models.ManyToManyField(blank=True, to='dcodex_carlson.VerseLabel'),
        ),
    ]
