# Generated by Django 2.2.2 on 2019-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_carlson', '0004_auto_20191016_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublocation',
            name='weighting',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
