# Generated by Django 3.0.8 on 2020-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_carlson', '0005_auto_20191024_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siglum',
            options={'ordering': ['name'], 'verbose_name_plural': 'Sigla'},
        ),
        migrations.AddField(
            model_name='attestation',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
